// Copyright 2026 The Zilkworm Authors
// SPDX-License-Identifier: Apache-2.0

/* RISC0 zkVM syscall interface for rv32im bare-metal C++ guest.
 *
 * References:
 *   risc0/zkvm/platform/src/syscall.rs   – ecall ABI
 *   risc0/zkvm/platform/src/memory.rs    – address constants
 *   risc0/zkvm/platform/src/lib.rs       – FD constants, WORD_SIZE
 *
 * RISC0 ecall convention (SOFTWARE type):
 *   t0  = RISC0_ECALL_SOFTWARE (2)
 *   t6  = Syscall enum value  (e.g. 12 = Read, 16 = Write)
 *   a0  = from-host buffer pointer (in/out; guest receive buffer)
 *   a1  = from-host buffer capacity (bytes; in/out: host fills this many)
 *   a2  = pointer to NUL-terminated syscall name C string
 *   a3  = arg0
 *   a4  = arg1
 *   a5  = arg2
 * Return: a0 = result0, a1 = result1
 */

#pragma once
#include <cstddef>   // size_t
#include <cstdint>   // uint8_t, uint32_t
#include <cstring>   // strlen
#include <string_view>

// ─── Platform word size ─────────────────────────────────────────────────────
// RISC0 is rv32im: 32-bit pointers, 32-bit registers.
using uintType = uint32_t;

// ─── File descriptors ───────────────────────────────────────────────────────
constexpr uint32_t RISC0_FD_STDIN   = 0;
constexpr uint32_t RISC0_FD_STDOUT  = 1;
constexpr uint32_t RISC0_FD_STDERR  = 2;
constexpr uint32_t RISC0_FD_JOURNAL = 3;  // public-output journal

// ─── ecall type codes (t0 register) ─────────────────────────────────────────
constexpr uint32_t RISC0_ECALL_HALT      = 0;
constexpr uint32_t RISC0_ECALL_INPUT     = 1;
constexpr uint32_t RISC0_ECALL_SOFTWARE  = 2;
constexpr uint32_t RISC0_ECALL_SHA       = 3;
constexpr uint32_t RISC0_ECALL_BIGINT    = 4;
constexpr uint32_t RISC0_ECALL_POSEIDON2 = 7;

// ─── Halt codes (low byte of a0) ────────────────────────────────────────────
constexpr uint32_t RISC0_HALT_TERMINATE = 0;
constexpr uint32_t RISC0_HALT_PAUSE     = 1;

// ─── SOFTWARE ecall Syscall enum values (t6 register) ───────────────────────
// From risc0/zkvm/platform/src/syscall.rs  enum Syscall
constexpr uint32_t RISC0_SYSCALL_LOG    = 8;
constexpr uint32_t RISC0_SYSCALL_PANIC  = 9;
constexpr uint32_t RISC0_SYSCALL_READ   = 12;
constexpr uint32_t RISC0_SYSCALL_WRITE  = 16;

// ─── Syscall name strings ────────────────────────────────────────────────────
// Generated by declare_syscall!(SYS_X) in risc0/zkvm/platform/src/syscall.rs:
//   format: module_path!() "::" stringify!(NAME) "\0"
//   where module_path for nr module = "risc0_zkvm_platform::syscall::nr"
extern "C" {
    extern const char RISC0_NR_SYS_LOG[];    // "risc0_zkvm_platform::syscall::nr::SYS_LOG"
    extern const char RISC0_NR_SYS_PANIC[];  // "risc0_zkvm_platform::syscall::nr::SYS_PANIC"
    extern const char RISC0_NR_SYS_READ[];   // "risc0_zkvm_platform::syscall::nr::SYS_READ"
    extern const char RISC0_NR_SYS_WRITE[];  // "risc0_zkvm_platform::syscall::nr::SYS_WRITE"
}

// ─── ReadVecResult – returned by read_vec_raw() ──────────────────────────────
// Must match the ABI used by z6m/stateless.hpp (same struct on rv32im).
struct ReadVecResult {
    uint8_t *ptr;
    size_t   len;
    size_t   capacity;
};

// ─── Function declarations (defined in risc0_runtime.cpp) ───────────────────
extern "C" {
    // Halt execution with the given exit code (never returns).
    [[noreturn]] void syscall_halt(uint8_t exit_code);

    // Write nbytes from buf to fd.  If fd == RISC0_FD_JOURNAL, bytes are
    // also accumulated in the journal buffer for hashing at halt time.
    void syscall_write(uint32_t fd, const uint8_t *buf, size_t nbytes);

    // Read one length-prefixed input frame from stdin (fd 0).
    // The frame format is: [4-byte LE length] [length bytes].
    ReadVecResult read_vec_raw() noexcept;

    // Panic: write msg to stderr and halt with exit code 1.
    [[noreturn]] void sys_panic(const uint8_t *msg, size_t len);
}

// ─── Convenience print helpers ───────────────────────────────────────────────
[[gnu::always_inline]] static inline void sys_print(const char *s) noexcept {
    syscall_write(RISC0_FD_STDOUT,
                  reinterpret_cast<const uint8_t *>(s), std::strlen(s));
}
[[gnu::always_inline]] static inline void sys_println(const char *s) noexcept {
    syscall_write(RISC0_FD_STDOUT,
                  reinterpret_cast<const uint8_t *>(s), std::strlen(s));
    syscall_write(RISC0_FD_STDOUT,
                  reinterpret_cast<const uint8_t *>("\n"), 1);
}
[[gnu::always_inline]] static inline void sys_println(std::string_view s) noexcept {
    syscall_write(RISC0_FD_STDOUT,
                  reinterpret_cast<const uint8_t *>(s.data()), s.size());
    syscall_write(RISC0_FD_STDOUT,
                  reinterpret_cast<const uint8_t *>("\n"), 1);
}
